language: node_js

node_js:
 - "node"

services:
  - docker

# so the functional tests will work
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

before_script:
  - cd $TRAVIS_BUILD_DIR

script:
  - PACKAGE_MANAGER=npm ./runtests.sh
