FROM ubuntu:20.04

LABEL maintainer="Erwin Dondorp <saltgui@dondorp.com>"
LABEL name=salt-master
LABEL project="SaltGUI testing"
LABEL version=3003

ENV SALT_VERSION=3003
ENV DEBIAN_FRONTEND=noninteractive

# fix ubuntu
# see https://askubuntu.com/questions/1235914/hash-sum-mismatch-error-due-to-identical-sha1-and-md5-but-different-sha256
RUN mkdir /etc/gcrypt && echo all >> /etc/gcrypt/hwf.deny

# add saltstack key and install dependencies
RUN apt-get update \
  && apt-get install curl net-tools gnupg2 dirmngr --yes --no-install-recommends \
  && apt-key adv --fetch-keys http://repo.saltstack.com/py3/ubuntu/20.04/amd64/archive/${SALT_VERSION}/SALTSTACK-GPG-KEY.pub \
  && echo "deb http://repo.saltstack.com/py3/ubuntu/20.04/amd64/archive/${SALT_VERSION} focal main" > /etc/apt/sources.list.d/saltstack.list \
  # install salt-master and salt-api, dependencies
  && apt-get update \
  && apt-get install salt-master=${SALT_VERSION}* salt-api=${SALT_VERSION}* python3-cherrypy3 --yes --no-install-recommends \
  # add a user for the frontend salt:salt
  && useradd -m -s/bin/bash -p $(openssl passwd -1 salt) salt \
  # install supervisor
  && apt-get install supervisor --yes --no-install-recommends \
  # show which versions are installed
  && dpkg -l | grep salt- \
  # cleanup temporary files
  && rm -rf /var/lib/apt/lists/* \
  && apt-get -y autoremove \
  && apt-get clean

# copy supervisord configuration
COPY ./conf/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# some volume configuration for the saltmaster
VOLUME ["/pki", "/var/cache/salt", "/var/log/salt"]
EXPOSE 3333 4505 4506

# define main container command
CMD /usr/bin/supervisord
