FROM ubuntu
MAINTAINER Martijn Jacobs <martijn@devopsconsulting.nl>

ENV REFRESHED_ON "7 Mar 2018"
ENV DEBIAN_FRONTEND noninteractive

# some handy stuff to have
RUN apt-get update && apt-get install curl --yes && apt-get install iproute2 --yes && apt-get install netcat-openbsd -y 

# add saltstack key
RUN curl --fail --silent --show-error --location https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub | apt-key add -
RUN echo 'deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main' > /etc/apt/sources.list.d/saltstack.list

# install salt-minion
RUN apt-get update && apt-get install salt-minion --yes

# copy the minion configuration
ADD ./conf/minion /etc/salt/minion

# copy the wait for saltmaster script to /usr/local/bin
ADD ./scripts/wait-for-saltmaster.sh /usr/local/bin/wait-for-saltmaster.sh
