FROM debian
MAINTAINER Martijn Jacobs <martijn@devopsconsulting.nl>

ENV REFRESHED_ON "7 Mar 2018"
ENV DEBIAN_FRONTEND noninteractive

# some handy stuff to have
RUN apt-get update && apt-get install curl --yes && apt-get install gnupg --yes

# add saltstack key
RUN curl --fail --silent --show-error --location https://repo.saltstack.com/apt/debian/9/amd64/latest/SALTSTACK-GPG-KEY.pub | apt-key add -
RUN echo 'deb http://repo.saltstack.com/apt/debian/9/amd64/latest stretch main' > /etc/apt/sources.list.d/saltstack.list

# install salt-minion
RUN apt-get update && apt-get install salt-minion --yes

# copy the minion configuration
ADD ./conf/minion /etc/salt/minion
