FROM ubuntu:26.04

# Reduce the amount of consecutive RUN instructions:
# SONARQUBE disable-check S7031

LABEL maintainer="Erwin Dondorp <saltgui@dondorp.com>"
LABEL name="salt-minion"
LABEL project="SaltGUI testing"
LABEL version="3007.14"

ENV SALT_VERSION="3007.14"
ENV DEBIAN_FRONTEND="noninteractive"

# make download possible, make encrypted password generation possible
RUN apt-get update
RUN apt-get install --yes --no-install-recommends ca-certificates curl openssl adduser

# add a user for the frontend salt:salt
RUN adduser --disabled-password --gecos "" salt
RUN usermod -s /bin/bash -p "$(openssl passwd -1 salt)" salt

# install salt-minion
# not using repo, so must explicitly do all packages
# Use TARGETARCH to get the correct architecture for multi-platform builds
ARG TARGETARCH
RUN curl -o "salt-common_${SALT_VERSION}.deb" \
  "https://packages.broadcom.com/artifactory/saltproject-deb/pool/salt-common_${SALT_VERSION}_${TARGETARCH}.deb"
RUN curl -o "salt-minion_${SALT_VERSION}.deb" \
  "https://packages.broadcom.com/artifactory/saltproject-deb/pool/salt-minion_${SALT_VERSION}_${TARGETARCH}.deb"
RUN apt install --yes --no-install-recommends \
  "./salt-common_${SALT_VERSION}.deb" \
  "./salt-minion_${SALT_VERSION}.deb"

# cleanup temporary files
RUN rm -rf /var/lib/apt/lists/* *.deb \
  && apt-get -y autoremove \
  && apt-get clean

# copy the minion configuration
COPY ./conf/minion /etc/salt/minion

ENV CRYPTOGRAPHY_OPENSSL_NO_LEGACY=true

# define main container command
CMD ["/usr/bin/salt-minion"]
