FROM ubuntu:22.04

LABEL maintainer="Erwin Dondorp <saltgui@dondorp.com>"
LABEL name=saltgui-nginx
LABEL project="SaltGUI testing"
LABEL version=1.18.0

ENV NGINX_VERSION=1.18.0
ENV DEBIAN_FRONTEND=noninteractive

# fix ubuntu
# see https://askubuntu.com/questions/1235914/hash-sum-mismatch-error-due-to-identical-sha1-and-md5-but-different-sha256
RUN mkdir /etc/gcrypt && echo all >> /etc/gcrypt/hwf.deny

RUN apt-get update \
  # install nginx
  && apt-get install -y nginx=${NGINX_VERSION}* --no-install-recommends \
  # show which versions are installed
  && dpkg -l | grep nginx \
  # cleanup temporary files
  && rm -rf /var/lib/apt/lists/* \
  && apt-get -y autoremove \
  && apt-get clean \
  # cleanup nginx
  && rm /etc/nginx/sites-enabled/default \
  # configure docker nginx logging
  && ln -sf /dev/stdout /var/log/nginx/access.log \
  && ln -sf /dev/stderr /var/log/nginx/error.log

# copy the nginx configuration
COPY ./conf/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./conf/nginx/default.conf /etc/nginx/conf.d/default.conf

# define main container command
CMD ["nginx", "-g", "daemon off;"]
