version: '3'
services:
  saltmaster-local:
    image: erwindon/saltgui-saltmaster-tls:3007.6
    hostname: saltmaster-local
    ports:
      # for SaltGUI (https)
      - 3334:3334
      # for additional minions, enable as needed
      # but note that this may conflict a local saltstack
      #- 4505:4505
      #- 4506:4506
    volumes:
    - ./srv/:/srv/
    - ./conf/master-tls:/etc/salt/master
    - ../saltgui:/saltgui
    - ssl_certs:/etc/ssl/saltgui

  saltminion-ubuntu:
    image: erwindon/saltgui-saltminion-ubuntu:3007.6
    hostname: saltminion-ubuntu
    depends_on:
      - saltmaster-local
    restart: on-failure

  saltminion-debian:
    image: erwindon/saltgui-saltminion-debian:3007.6
    hostname: saltminion-debian
    depends_on:
      - saltmaster-local
    restart: on-failure

  saltminion-centos:
    image: erwindon/saltgui-saltminion-centos:3007.6
    hostname: saltminion-centos
    depends_on:
      - saltmaster-local
    restart: on-failure

volumes:
  ssl_certs:
