version: '3'
services:
  saltmaster-ssl:
    image: erwindon/saltgui-saltmaster:3007.4
    hostname: saltmaster-ssl
    ports:
      - 4505:4505
      - 4506:4506
      - 8443:8443   # HTTPS SaltGUI direct
    volumes:
      - ./srv/:/srv/
      - ./conf/master-ssl:/etc/salt/master
      - ./ssl:/etc/ssl/saltgui:ro
    environment:
      - SALTGUI_SSL_ENABLED=true

  saltminion-ubuntu-ssl:
    image: erwindon/saltgui-saltminion-ubuntu:3007.4
    hostname: saltminion-ubuntu-ssl
    depends_on:
      - saltmaster-ssl
    restart: on-failure

  saltminion-debian-ssl:
    image: erwindon/saltgui-saltminion-debian:3007.4
    hostname: saltminion-debian-ssl
    depends_on:
      - saltmaster-ssl
    restart: on-failure

  saltminion-centos-ssl:
    image: erwindon/saltgui-saltminion-centos:3007.4
    hostname: saltminion-centos-ssl
    depends_on:
      - saltmaster-ssl
    restart: on-failure
