version: '3'
services:
  saltmaster-local:
    image: erwindon/saltgui-saltmaster:3007.4
    hostname: saltmaster-local
    ports:
      - 4505:4505
      - 4506:4506
      - 3333:3333
    volumes:
    - ./srv/:/srv/
    - ./conf/master:/etc/salt/master
    # Removed the ../saltgui:/saltgui mount to test clean deployment

  saltminion-ubuntu:
    image: erwindon/saltgui-saltminion-ubuntu:3007.4
    hostname: saltminion-ubuntu
    depends_on:
      - saltmaster-local
    restart: on-failure

  saltminion-debian:
    image: erwindon/saltgui-saltminion-debian:3007.4
    hostname: saltminion-debian
    depends_on:
      - saltmaster-local
    restart: on-failure

  saltminion-centos:
    image: erwindon/saltgui-saltminion-centos:3007.4
    hostname: saltminion-centos
    depends_on:
      - saltmaster-local
    restart: on-failure